"""Create table circuits

Revision ID: 20d0b7028695
Revises: 68542b4570f9
Create Date: 2026-02-21 17:27:30.868277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d0b7028695'
down_revision: Union[str, Sequence[str], None] = '68542b4570f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.String(), nullable=False),
    sa.Column('wikipedia_url', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('loc_latitude', sa.String(), nullable=True),
    sa.Column('loc_longitude', sa.String(), nullable=True),
    sa.Column('loc_locality', sa.String(), nullable=True),
    sa.Column('loc_country', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circuits_circuit_id'), 'circuits', ['circuit_id'], unique=True)
    op.create_index(op.f('ix_circuits_id'), 'circuits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_circuits_id'), table_name='circuits')
    op.drop_index(op.f('ix_circuits_circuit_id'), table_name='circuits')
    op.drop_table('circuits')
    # ### end Alembic commands ###
