"""Alter column meeting_key_openf1 to session_key_openf1 on table sessions

Revision ID: 23ddb2c268d0
Revises: 9f5291783892
Create Date: 2026-02-24 01:16:36.532624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23ddb2c268d0'
down_revision: Union[str, Sequence[str], None] = '9f5291783892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('session_key_openf1', sa.Integer(), nullable=True))
    op.drop_column('sessions', 'meeting_key_openf1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('meeting_key_openf1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('sessions', 'session_key_openf1')
    # ### end Alembic commands ###
