"""Add meeting_key_openf1 and created_at columns to sessions table.

Revision ID: 255634711e00
Revises: 5d90425c0cd7
Create Date: 2026-02-24 01:08:59.448523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '255634711e00'
down_revision: Union[str, Sequence[str], None] = '5d90425c0cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('meeting_key_openf1', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'created_at')
    op.drop_column('sessions', 'meeting_key_openf1')
    # ### end Alembic commands ###
