"""Add meeting_key_openf1 and created_at columns to races table.

Revision ID: 9f5291783892
Revises: 255634711e00
Create Date: 2026-02-24 01:14:37.850874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5291783892'
down_revision: Union[str, Sequence[str], None] = '255634711e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('meeting_key_openf1', sa.Integer(), nullable=True))
    op.add_column('races', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('races', 'created_at')
    op.drop_column('races', 'meeting_key_openf1')
    # ### end Alembic commands ###
